version: 2
project_name: utasker
...
    binary: utasker
...
brews:
  - name: utasker
    homepage: "https://github.com/U-SITE-SAS-BIC/utasker"
    description: "Offline-first, project-aware CLI task manager"
    license: "Apache-2.0"
    repository:
      owner: U-SITE-SAS-BIC
      name: homebrew-utasker
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    install: |
      bin.install "task"
